---
- name: latest Apache version installed
  yum:
    name: {{ packages_to_install }}
    state: latest

me: firewalld enabled and running
  service:
    name: firewalld
    enabled: true
    state: started

